### PR TITLE
Fix the issue where finish() runs twice

### LINKED ISSUE #56: finish() calls twice on SIGTERM
Discussion for a new bug discovered in #27

### PR DESCRIPTION
**Pull request by nonnymoose**
I did this by calling the `exit` function at the end of `finish()`.
Should fix #56 .

### CODE REVIEW

**Comment by nonnymoose** [comment]
@lezsakdomi Do you think this is an acceptable solution to the problem?
This way, if the behavior of perl changes again for some reason, it will still clean up properly.

**Comment by nonnymoose** [comment]
Whoops, looks like I merged it anyway by resolving the conflicts. @lezsakdomi Let me know if there's a problem.

**Comment by lezsakdomi** [comment]
@nonnymoose Isn't there any way to name the function different and trap the signal for it?

**Comment by nonnymoose** [comment]
@lezsakdomi Yes, but either way, it will trigger the `finish()` at the end of the program _and_ the SIGTERM `finish()`, so I felt like it would be a better idea to just exit at the end of `finish()` so it won't be executed twice.

This has the added benefit that it will still work if Perl's behavior changes back to what it was while I was originally developing psr.

**Comment by lezsakdomi** [comment]
@nonnymoose Ok. Then do it the python way:
1. Leave the call at the end of file, as originally
2. Before entering mainloop: Trap a function, which tracks wether SIGTERM got (or simply terminates mainloop, in this case skip step 3 :) )
3. In mainloop: Check in every run wether we should quit (or do it more perlic)
4. After mainloop: Cancel that trap (...) (and call `finish`)

**Comment by nonnymoose** [comment]
@lezsakdomi Okay, I will do that.
It is not necessary, however, to remove the trap after mainloop because mainloop won't be checking that flag any more.
Should I still do it for good practice?

**Comment by lezsakdomi** [comment]
@nonnymoose: One more function, which wastes CPU time :)
So yes, do for good practice, please. Maybe in the future it would matter.

**Pull request merged**
