### PR TITLE
Assertions for file operations

### LINKED ISSUE #20: More assertion
For me - this program fails. But I don't know why.
This issue is just a placeholder to be able to create an appropriate branch and track discussions :)

### PR DESCRIPTION
**Pull request by lezsakdomi**
Doesn't close #20 fully yet

### CODE REVIEW

**Comment by lezsakdomi** [comment]
Any more ideas?

**Comment by nonnymoose** [comment]
@lezsakdomi I think that's everything. Ready to merge?

**Comment by lezsakdomi** [comment]
@nonnymoose Yes, but please review the changes. I'm not sure if I followed the usual practices :)

**Comment by nonnymoose** [comment]
@lezsakdomi I will merge it now.

**Pull request merged**
