### PR TITLE
Add info message about shift in break

### LINKED ISSUE #63: Inform users explicit about the required shift for pause
Pulled #56 to here (a part of it)

### PR DESCRIPTION
**Pull request by lezsakdomi**
Fixes #63

### CODE REVIEW

**Comment by nonnymoose** [comment]
Yes! Let's do it!

**Comment by lezsakdomi** [comment]
Will interfer with#53

**Comment by lezsakdomi** [comment]
Late...

**Comment by nonnymoose** [comment]
@lezsakdomi Sorry. I reverted it, though.

**Pull request merged**
