### PR TITLE
Create make rule for README.md

### PR DESCRIPTION
**Pull request by lezsakdomi**
Solves #50

### CODE REVIEW

**Comment by lezsakdomi** [comment]
@nonnymoose Please review my idea!
I created  markdown-preset.m4 to make editing `README.md.m4` user-friendly

**Comment by nonnymoose** [comment]
@lezsakdomi This is a great idea; however, I am unfamiliar with m4 so you would need to maintain it, at least for now. When I tried making it, it left some stuff in the output file:
```
m4_changeword([\.\/_a-zA-Z0-9]+)Usage: ./xsr [options] [outfile]

Options:

  -o|--out outfile		Output file name (also can be first argument)
  -e|--edit-images-before-save	Edit images before saving file
  -c|--image-extension ext	Extension of image output (png or jpg)
  -u|--capture-focused		Captured the focused window only
  --no-mouse			Do not add mouse to screenshots
  --countdown[=seconds]		Display countdown (default 5)
  --no-countdown			Don't display countdown
  -h|--help			Print this message
m4_changeword([_a-zA-Z][_a-zA-Z0-9]*)
```

**Comment by lezsakdomi** [comment]
@nonnymoose Ouch, my fault. I've left the ugly method in the file, now it's more robust, now should work!

**Comment by lezsakdomi** [comment]
BTW it's okay for me to maintain it, at least if you mention me when I'm required.

**Comment by nonnymoose** [comment]
@lezsakdomi This should work now that I've reverted #64 .

**Pull request merged**
